'use strict';
const PWA_VERSION='1.0.0';
const AVATARS=['animal-capivara','animal-gato','animal-raposa','pessoa-01','pessoa-02','pessoa-03','pessoa-04','pessoa-05','pessoa-06','simbolo-broto','simbolo-estrela','simbolo-planeta'];
const AVATAR_COLORS=['#dbeee2','#deebf8','#eee2f5','#f7e7d4','#263e33','#203249','#382d48','#49362a'];
const MAIN_NAV=[['home','Início','home'],['treatment','Tratamento','med'],['food','Alimentação','food'],['movement','Exercícios','move'],['meditation','Bem-estar','heart']];
let installPrompt=null,onboardingPending=false,recoveryToShow=null,lofiTimer=null,journeyRaf=0,returnSplash=false;
Object.assign(JOURNEY_NAMES,Object.fromEntries(ViaJourney.marks.map(n=>[n,ViaJourney.THEMES[ViaJourney.themeIndex(n)][0]])));
NAV2.splice(0,NAV2.length,...MAIN_NAV,['journey','Minha caminhada','chart'],['water','Água','water'],['progress','Progresso','chart'],['exams','Exames','note'],['wellbeing','Humor e sono','heart'],['symptoms','Sintomas','heart'],['notes','Diário','note'],['reports','Resumo para consulta','calendar']);
function avatarUrl(value){return `assets/avatares/via-avatar-${AVATARS.includes(value)?value:'animal-gato'}-512.png`}
function avatarMarkup(size=''){const p=appData.profile;return `<img class="profile-avatar ${size}" style="background:${AVATAR_COLORS.includes(p.avatarColor)?p.avatarColor:AVATAR_COLORS[0]}" src="${avatarUrl(p.avatar)}" alt="Avatar do perfil">`}
function isInstalled(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelectorAll('[data-install]').forEach(b=>b.hidden=isInstalled())});
window.addEventListener('appinstalled',()=>{installPrompt=null;document.querySelectorAll('[data-install]').forEach(b=>b.hidden=true);toast('VIA instalado. Seu caminho vai com você.')});
async function installApp(){if(isInstalled())return toast('Você já está usando o aplicativo instalado.');if(installPrompt){await installPrompt.prompt();installPrompt=null;return}const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);modal('Instalar o VIA',location.protocol==='file:'?'<p>Para instalar, abra o endereço HTTPS do VIA publicado. Um arquivo aberto direto do computador permite visualizar, mas não instalar como PWA.</p>':ios?'<p>No Safari, abra <strong>Compartilhar</strong>, escolha <strong>Adicionar à Tela de Início</strong> e confirme em <strong>Adicionar</strong>.</p>':'<p>No menu do navegador, procure <strong>Instalar aplicativo</strong> ou <strong>Adicionar à tela inicial</strong>. A disponibilidade depende do navegador e de o endereço estar em HTTPS.</p>')}
function publicShell(){document.body.classList.remove('logged');$('#sidebar').hidden=true;$('#nav').hidden=true;$('#quick').hidden=true;$('#petGuide').hidden=true;$('#main').className='';$('#header').innerHTML=`<div class="logo">via<em>Um passo de cada vez</em></div>${btn(icon('moon'),'toggleTheme()','secondary')}`}
function welcomeView(){publicShell();$('#main').innerHTML=`<section class="welcome"><div><span class="eyebrow">VIA · JORNADA DE EMAGRECIMENTO</span><h1>O seu caminho.<br>Uma companhia<br>todos os dias.</h1><p>Tratamento, alimentação, movimento e bem-estar juntos. Registre seus cuidados e descubra cada passo da sua jornada.</p><div class="welcome-actions"><button class="btn secondary full" data-install ${isInstalled()?'hidden':''} onclick="installApp()">${icon('download')} Instalar aplicativo</button>${btn('Começar agora',"authView(true)",'full')}${btn('Já tenho uma conta',"authView(false)",'secondary full')}${btn('Recuperar dados de um backup','importForm()','plain full')}</div><small>Seus registros ficam neste aparelho. Exporte um backup para levar seu caminho a outro dispositivo.</small></div><img src="assets/gato-ola.png" alt="O gato VIA dá boas-vindas à sua jornada"></section>`}
function authView(register=false){publicShell();$('#main').innerHTML=`<section class="auth pwa-auth">${btn('← Voltar','welcomeView()','plain')}<img class="auth-cat" src="assets/gato-ola.png" alt="Gato VIA"><h1>${register?'Vamos começar?':'Bom te ver de volta.'}</h1><p>${register?'Crie seu perfil para começar seu caminho.':'Entre para continuar de onde você parou.'}</p><form id="authForm">${register?field('name','Como podemos te chamar?','text','','required maxlength="80" autocomplete="name"'):''}${field('email','E-mail','email','','required maxlength="150" autocomplete="username"')}${field('password','Senha','password','','required minlength="8" maxlength="200" autocomplete="'+(register?'new-password':'current-password')+'"')}${register?field('confirm','Confirmar senha','password','','required minlength="8" maxlength="200" autocomplete="new-password"'):check('remember','Continuar conectado neste aparelho',true)}<p id="authError" class="error" role="alert"></p><button class="btn full">${register?'Criar minha conta':'Entrar'}</button></form>${register?'':btn('Esqueci minha senha','recoverPassword()','plain full')}${btn('Recuperar dados de um backup','importForm()','plain full')}<small>Conta local deste aparelho. O e-mail identifica seu perfil; esta versão não envia mensagens nem sincroniza com a nuvem.</small></section>`;
$('#authForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)),email=v.email.trim().toLowerCase(),b=e.target.querySelector('button');b.disabled=true;try{if(register){if(!v.name.trim())throw Error('Informe seu nome.');if(v.password!==v.confirm)throw Error('As senhas precisam ser iguais.');if(Object.values(accounts).some(a=>a.email===email))throw Error('Este e-mail já tem um perfil neste aparelho.');const id=uid(),salt=uid(),code=makeRecoveryCode(),recoverySalt=uid();accounts[id]={email,salt,hash:await passwordHash(v.password,salt),recovery:{salt:recoverySalt,hash:await passwordHash(normalizeCode(code),recoverySalt)},data:blank(v.name.trim())};accounts[id].data.settings.celebrations={motion:true,sound:true};accounts[id].data.settings.haptics=true;if(!persist()){delete accounts[id];return}recoveryToShow=code;enter(id,true,true)}else{const match=Object.entries(accounts).find(([,a])=>!a.demo&&a.email===email);if(!match||await passwordHash(v.password,match[1].salt)!==match[1].hash)throw Error('E-mail ou senha incorretos.');enter(match[0],!!v.remember,false)}}catch(err){$('#authError').textContent=err.message}finally{b.disabled=false}}}
function makeRecoveryCode(){return Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase().match(/.{4}/g).join('-')}
function normalizeCode(s){return String(s).replace(/[^a-f0-9]/gi,'').toUpperCase()}
function recoveryCard(code){modal('Guarde seu código de recuperação',`<p>Este código permite definir outra senha para seu perfil neste aparelho. Guarde-o fora do VIA, em um lugar privado.</p><code class="recovery-code">${esc(code)}</code><p>Ele não substitui um backup dos registros. Se os dados do navegador forem apagados, restaure seu backup.</p>${btn('Baixar meu código',`downloadRecovery('${code}')`,'secondary full')}${btn('Guardei meu código','closeModal()','full')}`)}
function downloadRecovery(code){downloadBlob(new Blob([`VIA — código de recuperação\nPerfil: ${accounts[accountId].email}\n${code}\nGuarde em local privado. Este código não contém seus registros.\n`],{type:'text/plain'}),'via-codigo-recuperacao.txt')}
function recoverPassword(){form('Recuperar minha senha',field('email','E-mail do perfil','email','','required')+field('code','Código de recuperação','text','','required autocomplete="off"')+field('password','Nova senha','password','','required minlength="8" maxlength="200"')+field('confirm','Confirmar nova senha','password','','required minlength="8" maxlength="200"'),async v=>{if(v.password!==v.confirm)throw Error('As senhas precisam ser iguais.');const match=Object.entries(accounts).find(([,a])=>a.email===v.email.trim().toLowerCase()&&!a.demo);if(!match?.[1].recovery||await passwordHash(normalizeCode(v.code),match[1].recovery.salt)!==match[1].recovery.hash)throw Error('Perfil ou código não confere. Se mudou de aparelho, importe seu backup primeiro.');const a=match[1],prev=clone(a),code=makeRecoveryCode(),salt=uid(),rs=uid();Object.assign(a,{salt,hash:await passwordHash(v.password,salt),recovery:{salt:rs,hash:await passwordHash(normalizeCode(code),rs)}});if(!persist()){accounts[match[0]]=prev;return}closeModal();recoveryToShow=code;enter(match[0],false,false);recoveryCard(code);recoveryToShow=null},'Definir nova senha')}
function renewRecovery(){form('Novo código de recuperação',field('password','Confirme sua senha','password','','required'),async v=>{const a=accounts[accountId];if(await passwordHash(v.password,a.salt)!==a.hash)throw Error('Senha incorreta.');const code=makeRecoveryCode(),salt=uid(),old=a.recovery;a.recovery={salt,hash:await passwordHash(normalizeCode(code),salt)};if(!persist()){a.recovery=old;return}recoveryCard(code)})}
function enter(id,remember,isNew=false){draftMeal=null;notified.clear();accountId=id;appData=migrateData(accounts[id].data);importPortableLibrary(appData);draftMeal=appData.mealDraft?clone(appData.mealDraft):null;sessionStorage.setItem(SESSION,id);if(remember)localStorage.setItem(SESSION,id);else localStorage.removeItem(SESSION);sub='';onboardingPending=!appData.onboarded;returnSplash=!onboardingPending;route=onboardingPending?'home':'journey';render();if(onboardingPending)onboarding(0);else toast('Bom te ver de volta. Vamos juntos, um passo de cada vez.')}
function onboarding(step){const stages=[['Um caminho para cuidar de você.','O VIA reúne seus registros de tratamento, refeições, água, exercícios e bem-estar. Você escolhe suas metas e constrói sua rotina.'],['Seu primeiro passo já tem valor.','Parabéns pela iniciativa e obrigado por escolher o VIA. Um acesso por dia faz você avançar. A cada 7 passos, uma dica; nos baús mensais, um brasão permanente.'],['Tudo por perto.','Em Tratamento, acompanhe aplicações, locais e doses registradas. Em Alimentação, monte refeições e receitas com seus ingredientes. Exercícios reúne os treinos ilustrados. Bem-estar oferece pausas guiadas e meditação. Água, exames, diário e progresso ficam no menu completo.']];if(step>=3){closeModal();profileForm(true);return}const [title,copy]=stages[step];modal(title,`<div class="onboarding"><img src="assets/gato-ola.png" alt="Gato VIA apresenta o aplicativo"><p>${copy}</p>${step===1?'<p class="small muted">Cada 7 dias completos sem acessar recuam um ponto. As insígnias ficam com você. No retorno após recuo, a presença é registrada no ponto em que você ficou.</p><div id="introViewport" style="height:280px;overflow:auto;border-radius:16px;background:#07130e"><div id="introMap"></div></div><button type="button" class="btn plain full" onclick="introChest()">Conhecer meu primeiro baú →</button>':''}${step===2?'<div class="intro-menus">'+MAIN_NAV.slice(1).map(x=>`<span>${icon(x[2])}${x[1]}</span>`).join('') :''}<small>${step+1} de 3</small>${btn(step===2?'Registrar meus dados iniciais':'Continuar',`onboarding(${step+1})`,'full')}</div>`);if(step===1){ViaJourney.mount($('#introMap'),{position:1,awards:[]},{onSelect:()=>toast('No passo 30, você recebe o brasão da floresta.')}).scrollToPoint()}}
function introChest(){const v=$('#introViewport'),c=$('#introMap');v.scrollTo({top:ViaJourney.coords(30).y*c.clientWidth/480-v.clientHeight*.5,behavior:wantsMotion()?'smooth':'auto'})}
function profileForm(onboard=false){profileFormV4(onboard);const sex=$('#f_sex');if(sex)sex.previousElementSibling.textContent='Gênero (opcional)';const count=$('#f_mealCount');if(count&&!count.querySelector('option[value="1"]'))count.insertAdjacentHTML('afterbegin','<option value="1">1</option>');$('#entryForm').insertAdjacentHTML('beforeend',`${btn('+ Medidas atuais','initialMeasures()','secondary full')}<p class="small muted">Distribua as refeições conforme sua rotina e orientação profissional. Quatro refeições são uma sugestão inicial editável.</p>`);}
function initialMeasures(){const dialog=document.createElement('dialog');dialog.className='via-crest-dialog';dialog.innerHTML=`<h2>Suas medidas atuais</h2><form>${['cintura','abdomen','quadril','peito','braco','coxa'].map((k,i)=>field(k,['Cintura','Abdômen','Quadril','Peito','Braço','Coxa'][i]+' (cm)','number','','min="1" max="400" step="0.1"')).join('')}<p class="error"></p><button class="btn">Salvar medidas</button><button class="btn secondary" type="button" data-cancel>Voltar</button></form>`;document.body.append(dialog);dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const vals=Object.fromEntries([...new FormData(e.target)].filter(([,v])=>v!=='').map(([k,v])=>[k,+v]));if(!Object.keys(vals).length){dialog.querySelector('.error').textContent='Preencha pelo menos uma medida.';return}if(change(d=>d.measurements.push({id:uid(),date:stamp(),...vals})))dialog.close()};dialog.showModal()}
function change(fn,msg='Salvo no seu dispositivo'){const ok=changeV4(fn,msg);if(ok&&msg)feedback();return ok}
function feedback(){if(!appData)return;unlockAudio();if(appData.settings.celebrations.sound){const c=getAudioContext();if(c){const o=c.createOscillator(),g=c.createGain();o.frequency.value=660;g.gain.setValueAtTime(.025,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.12);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.13);o.onended=()=>{o.disconnect();g.disconnect()}}}if(appData.settings.haptics!==false)navigator.vibrate?.(12)}
function render(){if(!appData)return;if(onboardingPending&&appData.onboarded){onboardingPending=false;route='journey';returnSplash=true;if(recoveryToShow){const code=recoveryToShow;recoveryToShow=null;setTimeout(()=>recoveryCard(code),300)}}renderV4();$('#nav').innerHTML=MAIN_NAV.map(([r,t,i])=>`<button class="${route===r?'active':''}" onclick="go('${r}')" ${route===r?'aria-current="page"':''}>${icon(i)}<span>${t}</span></button>`).join('');$('#header .v2-header-right')?.insertAdjacentHTML('afterbegin',btn(icon('note'),'allMenus()','plain pwa-more'));const profile=$('#header button[aria-label="Meu perfil"]');if(profile)profile.innerHTML=avatarMarkup();$('#petGuide').hidden=!appData.onboarded;$('#petGuide img').src=wantsMotion()?'assets/gato-animado.webp':'assets/gato-pausa.png';if(route==='notifications')$('#main').innerHTML=notificationsView();if(route==='profile')$('#main').classList.remove('v2-flow');if(route==='meditation')$('#main').insertAdjacentHTML('afterbegin',`<div class="tabs"><button onclick="go('meditation')">Meditação</button><button onclick="go('wellbeing')">Humor e sono</button></div>`);document.querySelectorAll('#sidebar small').forEach(e=>e.innerHTML=e.innerHTML.replace('Via 4','VIA · PWA 1'));}
function allMenus(){modal('Seu VIA',`<div class="menu-grid">${NAV2.map(([r,t,i])=>menu(i,t,`closeModal();go('${r}')`)).join('')}${menu('user','Meu perfil',"closeModal();go('profile')")}${menu('bell','Lembretes',"closeModal();go('notifications')")}</div>`)}
const HELP_COPY={home:'Uma visão do seu dia: água, refeições, próxima aplicação e atalhos para registrar seus cuidados.',treatment:'Cadastre o tratamento, registre a aplicação e o local no manequim, consulte o histórico e confira a matemática da dose com os dados completos do rótulo.',food:'Procure alimentos com ou sem acento. Adicione porções e complementos, monte receitas, edite sua biblioteca e retome os rascunhos.',movement:'Explore 200 treinos ilustrados, veja instruções em português, selecione favoritos e registre suas atividades.',meditation:'Escolha uma prática, posição, cor e áudio. Use a leitura de voz disponível no aparelho, retome uma pausa e acompanhe suas metas.',journey:'Cada presença diária avança um ponto. Explore os cenários, as dicas semanais, os baús e suas insígnias permanentes.',water:'Acompanhe a estimativa de água, ajuste sua meta e registre as quantidades que bebeu.',progress:'Consulte pesagens, medidas, fotos e registros do calendário.',exams:'Crie um grupo de exames, acrescente vários resultados e anote laboratório, médicos, datas e recomendações.',wellbeing:'Registre como se sente e acompanhe seu sono.',symptoms:'Anote sintomas e intensidade para conversar com o profissional que acompanha você.',notes:'Guarde pensamentos e observações no diário.',reports:'Reúna registros do período para levar à consulta.'};
function petHelp(){modal('Vamos juntos?',`<img class="guide-cat" src="assets/gato-ola.png" alt="Gato VIA"><p>Qual parte você quer conhecer?</p><div class="stack">${NAV2.map(([r,t,i])=>menu(i,t,`petExplain('${r}')`)).join('')}</div>${btn('Quero registrar algo agora','quickMenu()','full')}`)}
function petExplain(r){modal(NAV2.find(x=>x[0]===r)?.[1]||'Seu VIA',`<img class="guide-cat" src="assets/gato-pausa.png" alt="Gato VIA"><p>${HELP_COPY[r]||'Seus registros e preferências ficam aqui.'}</p>${btn('Abrir esta área',`closeModal();go('${r}')`,'full')}${btn('Voltar ao guia','petHelp()','plain')}`)}
function profileView(){const j=appData.journey;return `<div class="profile-hero">${avatarMarkup('large')}<div><span class="eyebrow">MEU VIA</span><h1>${esc(appData.profile.name)}</h1><p>${esc(accounts[accountId].email)}</p>${btn('Escolher avatar','chooseAvatar()','secondary')}</div></div><div class="profile-stats"><span><b>${j.visits.length}</b> dias presentes</span><span><b>${j.position}</b> passos</span><span><b>${j.awards.length}</b> conquistas</span></div><div class="pwa-two">${card('Sua coleção',`<div class="crest-grid">${j.awards.length?j.awards.map(a=>`<button onclick="badgeDetail(${a.mark})">${badgeArt(a.mark)}<small>${a.mark} passos</small></button>`).join(''):empty('Seu primeiro brasão espera no passo 30.')}</div>`)}${card('Vamos lá?',`<div class="profile-invite"><img src="assets/gato-pausa.png" alt="Gato VIA">${btn('Escolher um cuidado','quickMenu()','full')}</div>`)}</div>${card('Seu perfil e seus dados',menu('user','Editar dados e horários','profileForm()')+menu('chart','Medidas atuais','initialMeasures()')+menu('moon','Claro / escuro','toggleTheme()')+menu('bell','Sons, movimento e vibração','experienceSettings()')+menu('download','Exportar meu backup','exportData()')+menu('download','Recuperar dados','importForm()')+menu('shield','Novo código de recuperação','renewRecovery()')+menu('user','Trocar senha','changePassword()')+menu('download','Materiais sem internet','offlineLibrary()')+menu('download','Instalar aplicativo','installApp()')+menu('shield','Privacidade e fontes',"go('privacy')")+menu('note','Apagar meus registros','eraseRecords()')+menu('user','Excluir conta','deleteAccount()')+menu('arrow','Sair','logout()'))}`}
function chooseAvatar(){modal('Um perfil com seu jeito',`<div class="avatar-picker">${AVATARS.map(v=>`<button class="${appData.profile.avatar===v?'selected':''}" aria-label="Avatar ${v.replaceAll('-',' ')}" onclick="setAvatar('${v}')"><img src="${avatarUrl(v)}" alt="${v.replaceAll('-',' ')}"></button>`).join('')}</div><h3>Cor de fundo</h3><div class="avatar-colors">${AVATAR_COLORS.map(c=>`<button style="background:${c}" aria-label="Cor ${c}" onclick="setAvatarColor('${c}')"></button>`).join('')}</div>${btn('Concluir','closeModal();render()','full')}`)}
function setAvatar(v){if(AVATARS.includes(v)&&change(d=>d.profile.avatar=v,''))chooseAvatar()}
function setAvatarColor(v){if(AVATAR_COLORS.includes(v)&&change(d=>d.profile.avatarColor=v,''))chooseAvatar()}
function experienceSettings(){form('No seu ritmo',check('sound','Sons de confirmação e conquistas',appData.settings.celebrations.sound)+check('motion','Animações e confetes',appData.settings.celebrations.motion)+check('haptics','Vibração breve, quando disponível',appData.settings.haptics!==false),v=>{if(change(d=>{d.settings.celebrations={sound:!!v.sound,motion:!!v.motion};d.settings.haptics=!!v.haptics})){closeModal();render()}})}
function journeyTransition(j,now){if(j.lastVisit&&now<=j.lastVisit)return null;const missed=j.lastVisit?Math.max(0,dateOrdinal(now)-dateOrdinal(j.lastVisit)-1):0,penalty=Math.floor(missed/7),from=Math.min(366,j.position),to=penalty?Math.max(0,from-penalty):Math.min(366,from+1);const next={...j,position:to,lastVisit:now,visits:[...j.visits,now],awards:[...j.awards],history:[...j.history,{date:now,from,to,missed,penalty:Math.min(from,penalty)}]},earned=[];if(!penalty)for(const mark of JOURNEY_MARKS)if(from<mark&&to>=mark&&!next.awards.some(a=>a.mark===mark)){next.awards.push({mark,date:now});earned.push(mark)}return{next,event:{date:now,from,to,missed,penalty:Math.min(from,penalty),returning:penalty>0,earned}}}
function registerJourney(){if(!appData?.onboarded)return;const t=journeyTransition(appData.journey,journeyDay());if(!t)return;const prev=appData.journey;appData.journey=t.next;const season=activeSeason();if(season&&!appData.journey.memories?.some(m=>m.key===season.key)){appData.journey.memories=[...(appData.journey.memories||[]),{key:season.key,title:season.title,date:journeyDay(),position:t.next.position}]}accounts[accountId].data=appData;if(!persist()){appData.journey=prev;return}journeyEvent=t.event;if(t.event.earned.length)queueCelebration('Um novo brasão é seu!',JOURNEY_NAMES[t.event.earned.at(-1)]+' · conquista permanente.','badge');else if(t.event.returning)queueCelebration('Bom te ver de volta.','Seu caminho continua aqui. Vamos juntos, um passo de cada vez.','return');else if(t.event.to>0&&t.event.to!==t.event.from&&t.event.to%7===0)queueCelebration('Mais uma semana de passos!',weeklyTip(t.event.to)[1]);}
function weeklyTip(n){return[['Água por perto','Faça uma pausa para conferir sua água de hoje.'],['Um pouco de movimento','Um movimento confortável também faz parte do cuidado.'],['Seu momento de respirar','Encontre um apoio e acompanhe algumas respirações naturais.'],['Uma refeição de cada vez','Registre o que você comeu e conheça sua rotina.']][Math.max(0,Math.floor(n/7)-1)%4]}
function badgeArt(mark,locked=false){if(!JOURNEY_MARKS.includes(mark))return `<span class="legacy-badge" aria-label="Conquista anterior preservada">✦ ${mark}</span>`;return `<img class="real-crest ${locked?'locked':''}" src="assets/brasoes/brasao-${mark}.png" loading="lazy" alt="Brasão ${esc(JOURNEY_NAMES[mark])}, ${mark} passos${locked?', ainda não conquistado':''}">`}
function badgeDetail(n){const a=appData.journey.awards.find(x=>x.mark===n);modal(a?'Seu baú de conquistas':'Um baú no seu caminho',`${a?badgeArt(n):'<div class="closed-chest">'+icon('shield')+'</div>'}<h3>${esc(JOURNEY_NAMES[n]||'Conquista da versão anterior')}</h3><p>${a?'Conquistada em '+date(a.date)+'. Ela continua sua mesmo quando o percurso recua.':'Ao alcançar '+n+' passos, você abre este baú e recebe o brasão do ambiente.'}</p>`)}
function journeyView(){const j=appData.journey;return `<div class="v2-head"><div><span class="eyebrow">${returnSplash?'BOM TE VER POR AQUI':'MINHA CAMINHADA'}</span><h1>Um passo de cada vez.</h1><p>Passo ${j.position} · ${j.visits.length} dias presentes</p></div>${btn('× Visão geral',"returnSplash=false;go('home')",'secondary')}</div><div class="pwa-journey-layout"><section class="card trail-card"><div class="row"><label for="chapterPick" class="sr-only">Explorar ambiente</label><select id="chapterPick" onchange="jumpChapter(+this.value)">${ViaJourney.THEMES.map((t,i)=>`<option value="${i}" ${ViaJourney.themeIndex(j.position)===i?'selected':''}>${t[0]}</option>`).join('')}</select>${btn('◎ Meu ponto','centerJourney()','secondary')}</div><div id="trailViewport" class="trail-viewport" tabindex="0" aria-label="Caminho rolável: deslize para cima para avançar na paisagem"><div id="trailContent"></div></div><p class="small muted">A paisagem acompanha a rolagem. Explore com o dedo, mouse ou teclado.</p></section><aside>${card('Seus brasões',`<div class="crest-grid">${JOURNEY_MARKS.map(n=>`<button onclick="badgeDetail(${n})">${badgeArt(n,!j.awards.some(a=>a.mark===n))}<small>${n} passos</small></button>`).join('')}</div>`)}${card('Lembranças',`<p>As comemorações passam. Os momentos ficam guardados aqui.</p>${btn('Abrir meu álbum','seasonAlbum()','secondary full')}`)}${card('Seu caminho continua',`<p>Um avanço no primeiro acesso do dia. Cada 7 dias completos de ausência recuam um ponto. No retorno com recuo, você registra presença nesse ponto.</p><p>As insígnias ficam com você. O capítulo espacial conclui o percurso de 366 passos.</p>${btn('Preferências','journeySettings()','plain')}`)}</aside></div>`}
function wireJourney(){const j=appData.journey;ViaJourney.mount($('#trailContent'),{position:Math.min(366,j.position),awards:j.awards.map(a=>a.mark)},{assetBase:'assets/brasoes',onSelect:r=>badgeDetail(r.milestone)});$('#trailContent').onclick=e=>{const t=e.target.closest('[data-step]');if(!t)return;const n=+t.dataset.step;if(JOURNEY_MARKS.includes(n))badgeDetail(n);else if(n%7===0){const tip=weeklyTip(n);modal(tip[0],`<img class="guide-cat" src="assets/gato-ola.png" alt="Gato VIA"><p>${tip[1]}</p><small>Uma dica semanal. Os brasões estão nos baús mensais.</small>`)}};document.querySelectorAll('#trailContent [data-step]').forEach(el=>{if(+el.dataset.step%7===0){el.setAttribute('role','button');el.setAttribute('tabindex','0')}});$('#trailContent').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){const t=e.target.closest('[data-step]');if(t){e.preventDefault();$('#trailContent').onclick(e)}}};const svg=$('#trailContent svg'),cat=document.createElementNS('http://www.w3.org/2000/svg','image');cat.id='journeyCat';cat.setAttribute('width',83);cat.setAttribute('height',87);cat.setAttribute('href',wantsMotion()?'assets/gato-animado.webp':'assets/gato-pausa.png');cat.style.pointerEvents='none';svg.append(cat);drawSeason();centerJourney(true);const v=$('#trailViewport');let drag=null;v.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0||e.target.closest('[data-step]'))return;drag={y:e.clientY,top:v.scrollTop};v.setPointerCapture(e.pointerId)});v.addEventListener('pointermove',e=>{if(drag)v.scrollTop=drag.top+drag.y-e.clientY});v.addEventListener('pointerup',()=>drag=null);v.addEventListener('pointercancel',()=>drag=null)}
function moveJourneyMarker(n){const p=ViaJourney.coords(n),m=$('#via-current');m?.setAttribute('transform',`translate(${p.x} ${p.y})`);$('#journeyCat')?.setAttribute('x',p.x-42);$('#journeyCat')?.setAttribute('y',p.y-113)}
function scrollJourneyTo(n){const v=$('#trailViewport'),c=$('#trailContent');if(v&&c)v.scrollTop=ViaJourney.coords(n).y*c.clientWidth/480-v.clientHeight*.65}
function centerJourney(animate=false){if(!$('#trailContent'))return;cancelAnimationFrame(journeyRaf);const p=Math.min(366,appData.journey.position),event=journeyEvent;moveJourneyMarker(p);scrollJourneyTo(p);if(animate&&event&&wantsMotion()&&event.from!==event.to){const start=performance.now(),from=Math.min(366,event.from),duration=1500;$('#via-current circle')?.setAttribute('stroke',event.returning?'#929d98':'#d2ffe1');function frame(now){if(route!=='journey'||!$('#journeyCat'))return;const t=Math.min(1,(now-start)/duration),n=from+(p-from)*(t*t*(3-2*t));moveJourneyMarker(n);scrollJourneyTo(n);if(t<1)journeyRaf=requestAnimationFrame(frame)}journeyRaf=requestAnimationFrame(frame)}journeyEvent=null}
function jumpChapter(i){cancelAnimationFrame(journeyRaf);scrollJourneyTo(i*30+1)}
function activeSeason(now=new Date()){const m=now.getMonth()+1,d=now.getDate(),y=now.getFullYear();let s=null;if(m===12&&d>=29||m===1&&d<=7)s=['newyear','Ano-novo','firework','#ddc6ff',m===12?y+1:y];else if(m===12)s=['christmas','Natal','gift','#f4d4a5',y];else if(m===10&&d>=15||m===11&&d<=2)s=['halloween','Halloween','pumpkin','#ffb37b',y];else if(m===6&&d>=10)s=['june','Festas juninas','flags','#f2cfa2',y];else if(m===4&&d<=25)s=['easter','Páscoa','egg','#edbedd',y];return s?{key:s[0]+':'+s[4],title:s[1],shape:s[2],color:s[3]}:null}
function drawSeason(){const svg=$('#trailContent svg');if(!svg)return;svg.querySelector('#calendarDecor')?.remove();const s=activeSeason();if(!s)return;const layer=document.createElementNS('http://www.w3.org/2000/svg','g');layer.id='calendarDecor';layer.style.pointerEvents='none';layer.innerHTML=Array.from({length:7},(_,i)=>i*2-6).filter(d=>appData.journey.position+d>0&&appData.journey.position+d<=366).map((d,i)=>{const p=ViaJourney.coords(appData.journey.position+d);return `<use href="#scene-${s.shape}" x="${i%2?390:60}" y="${p.y-22}" width="32" height="32" color="${s.color}" opacity="${.75-Math.abs(d)*.07}"/>`}).join('');svg.insertBefore(layer,$('#via-current'))}
function seasonAlbum(){modal('Lembranças no caminho',(appData.journey.memories||[]).map(m=>`<div class="item"><strong>${esc(m.title)}</strong><p>${date(m.date)} · passo ${m.position}</p></div>`).join('')||empty('Quando você visitar o VIA em uma época comemorativa, a lembrança aparecerá aqui. As datas são aproximadas.'))}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function downloadWorkoutPDF(){const a=document.createElement('a');a.href='assets/200-easy-workouts.pdf';a.download='200-easy-workouts.pdf';a.click()}
function packCurrentAccount(){captureDraft();if(mSession){meditationElapsed();persistMeditation()}return{app:'Via',version:5,exportedAt:new Date().toISOString(),theme:document.documentElement.dataset.theme||'light',accounts:{[accountId]:clone(accounts[accountId])}}}
function bytes64(bytes){let s='';for(let i=0;i<bytes.length;i+=16384)s+=String.fromCharCode(...bytes.subarray(i,i+16384));return btoa(s)}
function from64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function backupKey(password,salt,usage){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:210000,hash:'SHA-256'},key,{name:'AES-GCM',length:256},false,usage)}
async function encryptBackup(data,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await backupKey(password,salt,['encrypt']),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(data)));return{app:'VIA encrypted backup',version:1,salt:bytes64(salt),iv:bytes64(iv),data:bytes64(new Uint8Array(encrypted))}}
async function decryptBackup(data,password){if(data.version!==1||typeof data.data!=='string')throw Error('Formato de backup criptografado inválido.');const key=await backupKey(password,from64(data.salt),['decrypt']);try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:from64(data.iv)},key,from64(data.data));return JSON.parse(new TextDecoder().decode(plain))}catch{throw Error('Senha do backup incorreta ou arquivo alterado.')}}
function exportData(){form('Guardar meu caminho',notice('Este backup contém somente seu perfil ativo. Escolha uma senha para proteger o arquivo e guarde-a: ela será necessária na restauração.')+field('password','Senha do backup','password','','required minlength="8" maxlength="200" autocomplete="new-password"')+field('confirm','Confirmar senha','password','','required minlength="8" maxlength="200"'),async v=>{if(v.password!==v.confirm)throw Error('As senhas precisam ser iguais.');downloadBlob(new Blob([JSON.stringify(await encryptBackup(packCurrentAccount(),v.password))],{type:'application/json'}),'via-backup-protegido-'+day()+'.json');closeModal();feedback();toast('Backup protegido gerado.')},'Baixar backup protegido')}
function validateBackup(b){const out=validateBackupV4(b);for(const a of Object.values(out.accounts)){if(a.recovery&&(!/^[a-f0-9]{64}$/.test(a.recovery.hash)||typeof a.recovery.salt!=='string'||a.recovery.salt.length>100))throw Error('Código de recuperação inválido no backup.');if(a.data.profile.avatar&&!AVATARS.includes(a.data.profile.avatar))delete a.data.profile.avatar;if(a.data.profile.avatarColor&&!AVATAR_COLORS.includes(a.data.profile.avatarColor))delete a.data.profile.avatarColor;for(const photo of a.data.photos)if(photo.dataUrl&&!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(photo.dataUrl))throw Error('Imagem inválida no backup.');const mem=a.data.journey.memories;if(mem&&(!Array.isArray(mem)||mem.length>1000||mem.some(x=>typeof x.key!=='string'||x.key.length>100||typeof x.title!=='string'||x.title.length>100||!/^\d{4}-\d{2}-\d{2}$/.test(x.date)||!Number.isInteger(x.position)||x.position<0||x.position>366)))throw Error('Álbum inválido.')}return out}
function importForm(){modal('Recuperar meus dados',`<p>Escolha um backup VIA, protegido por senha ou exportado pelas versões anteriores.</p><label for="backupFile">Arquivo de backup</label><input id="backupFile" type="file" accept=".json,application/json"><div id="backupUnlock"></div><p id="importError" class="error" role="alert"></p>`);$('#backupFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>40*1024*1024)throw Error('O arquivo excede 40 MB.');const parsed=JSON.parse(await file.text());if(parsed.app==='VIA encrypted backup'){$('#backupUnlock').innerHTML=`<form id="unlockForm">${field('password','Senha deste backup','password','','required')}<button class="btn">Desbloquear</button></form>`;$('#unlockForm').onsubmit=async ev=>{ev.preventDefault();const b=ev.target.querySelector('button');b.disabled=true;try{confirmImport(validateBackup(await decryptBackup(parsed,new FormData(ev.target).get('password'))))}catch(err){$('#importError').textContent=err.message}finally{b.disabled=false}}}else confirmImport(validateBackup(parsed))}catch(err){$('#importError').textContent=err.message||'Arquivo inválido.'}}}
function confirmImport(data){const incoming=Object.values(data.accounts),collisions=incoming.filter(a=>Object.values(accounts).some(x=>x.email===a.email));confirmBox('Restaurar este backup?',`Serão recuperados ${incoming.length} perfil(is). ${collisions.length?'Os perfis com o mesmo e-mail serão substituídos pelos dados deste arquivo. Exporte uma cópia atual antes de continuar.':'Os demais perfis deste aparelho serão mantidos.'}`,()=>{const prev=accounts,next=clone(accounts);for(const [id,a]of Object.entries(data.accounts)){for(const [key,existing]of Object.entries(next))if(existing.email===a.email)delete next[key];const safeId=next[id]?uid():id;next[safeId]=a}accounts=next;if(!persist()){accounts=prev;return}logout(false);document.documentElement.dataset.theme=data.theme;localStorage.setItem('via.theme',data.theme);welcomeView();toast('Dados recuperados. Entre com a senha do perfil do backup.')})}
function notificationsView(){const settings=appData.settings.notifications;return `<h1>Lembretes</h1><p>Um toque para lembrar dos seus cuidados.</p>${card('Avisos neste aparelho',`<p>Os avisos funcionam enquanto o VIA está aberto e em execução. Nesta versão, fechar o aplicativo não mantém alarmes agendados.</p>${btn('Permitir notificações','enableNotifications()','secondary full')}${btn('Testar um aviso','testNotification()','plain full')}`)}${card('Meus horários',Object.entries(NOTIFS).map(([k,l])=>{const s=settings[k]||{enabled:false,time:'09:00'};return `<div class="item"><label class="check"><input type="checkbox" ${s.enabled?'checked':''} onchange="notifChange('${k}','enabled',this.checked)">${l}</label><label for="notif_${k}">Horário</label><input id="notif_${k}" type="time" value="${s.time}" onchange="notifChange('${k}','time',this.value)"></div>`}).join(''))}${notice(`Silêncio entre ${esc(appData.profile.bed)} e ${esc(appData.profile.wake)}. As refeições também usam os horários definidos no perfil.`)}`}
async function enableNotifications(){if(!('Notification'in window))return toast('Este navegador não oferece notificações.');try{const result=await Notification.requestPermission();toast(result==='granted'?'Notificações permitidas.':'Permissão não concedida. Os lembretes continuam dentro do VIA.')}catch{toast('Não foi possível pedir permissão neste navegador.')}}
async function sendNotification(title,tag){toast(title);if(!('Notification'in window)||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker?.getRegistration();if(reg)await reg.showNotification(title,{body:'Um cuidado de cada vez. Abra o VIA para registrar.',icon:'assets/icon-192.png',badge:'assets/icon-192.png',tag});}catch{}}
function testNotification(){sendNotification('VIA · Seu caminho continua aqui','via-test')}
function notificationTick(){if(!appData||isSleep(time()))return;const t=time();Object.entries(appData.settings.notifications).forEach(([k,v])=>{const id=day()+k+t;if(!v.enabled||notified.has(id))return;let due=v.time===t;if(k==='meals')due=due||appData.profile.mealTimes.includes(t);if(k==='treatment'){const a=activeTreatment();if(!a||a.paused)return;const now=new Date(),startDate=new Date(a.start+'T12:00'),days=Math.round((new Date(day()+'T12:00')-startDate)/86400000);due=t===a.hour&&days>=0&&(a.interval===7?now.getDay()===+a.weekday:days%a.interval===0)}if(due){notified.add(id);sendNotification('VIA · '+NOTIFS[k],'via-'+id)}})}
function stopMeditationAudio(){clearInterval(lofiTimer);lofiTimer=null;stopMeditationAudioV4()}
function startMeditationAudio(){if(!mSession?.audio.startsWith('lofi-'))return startMeditationAudioV4();stopMeditationAudio();const ctx=getAudioContext();if(!ctx||!appData.settings.meditation.volume)return;const gain=ctx.createGain();gain.gain.value=appData.settings.meditation.volume*.1;gain.connect(ctx.destination);meditationAudio.push(gain);const type=mSession.audio,tempo=type==='lofi-night'?1800:1500;let beat=0;const chords=[[130.81,164.81,196,246.94],[110,130.81,164.81,196],[87.31,110,130.81,164.81],[98,123.47,146.83,174.61]];const play=()=>{const t=ctx.currentTime,chord=chords[Math.floor(beat/4)%4];for(const [i,f]of chord.entries()){const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f*(type==='lofi-night'?.5:1);g.gain.setValueAtTime(0,t+i*.025);g.gain.linearRampToValueAtTime(.22,t+i*.025+.06);g.gain.exponentialRampToValueAtTime(.0001,t+2.8);o.connect(g);g.connect(gain);o.start(t+i*.025);o.stop(t+3);meditationAudio.push(o,g);o.onended=()=>{o.disconnect();g.disconnect();meditationAudio=meditationAudio.filter(n=>n!==o&&n!==g)}}beat++};play();lofiTimer=setInterval(play,tempo);if(type==='lofi-rain'){const buffer=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.15;const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter();src.buffer=buffer;src.loop=true;filter.type='lowpass';filter.frequency.value=750;src.connect(filter);filter.connect(gain);src.start();meditationAudio.push(src,filter)}}
function progressView(){if(sub!=='photos')return progressViewV4()+(sub==='weight'?bodyProgress():'');return `<h1>Seu progresso</h1>${tabs([['weight','Peso'],['measures','Medidas'],['calendar','Calendário'],['photos','Fotos']],'photos')}<p>Registros visuais opcionais, guardados somente neste aparelho e no seu backup.</p>${btn('Adicionar foto','photoForm()','full')}<div class="photo-grid">${sorted(appData.photos).map(p=>card('',`${p.dataUrl?`<img src="${esc(p.dataUrl)}" alt="${esc(p.name||'Foto da jornada')}">`:''}<strong>${esc(p.name)}</strong><small>${when(p.date)}</small>${btn('Excluir',`removeLog('photos','${p.id}')`,'plain')}`)).join('')}</div>`}

function bodyProgress(){if(!appData.profile.initial||!appData.profile.goal)return '';const progress=pct()/100;const figure=t=>{const waist=48-t*9,hip=46-t*5;return `<svg viewBox="0 0 200 340" role="img" aria-label="Silhueta simbólica da meta"><circle cx="100" cy="40" r="25" fill="var(--green)" opacity=".7"/><path d="M83 65L82 80Q45 80 39 110L22 197Q19 211 31 211Q40 212 43 199L58 141Q${100-waist} 164 ${100-waist} 190Q${100-hip} 213 62 231L67 309Q66 323 80 323Q88 323 88 310L95 232H105L112 310Q111 323 124 323Q135 323 133 309L138 231Q${100+hip} 213 ${100+waist} 190Q${100+waist} 164 142 141L157 199Q160 212 169 211Q181 211 178 197L161 110Q155 80 118 80L117 65" fill="var(--green)" opacity=".55"/></svg>`};return card('Uma imagem do seu percurso',`<div class="body-progress"><div>${figure(0)}<strong>Início</strong><small>${fmt(appData.profile.initial)} kg</small></div><div>${figure(progress)}<strong>Agora</strong><small>${fmt(currentWeight())} kg</small></div></div><progress value="${pct()}" max="100"></progress><p class="small muted">Ilustração simbólica da progressão até sua meta. Não representa medidas reais nem prevê aparência ou composição corporal.</p>`)}

function photoForm(){form('Foto da sua jornada',field('name','Legenda','text','','required maxlength="80"')+dt()+'<label for="photoFile">Escolher foto</label><input type="file" id="photoFile" accept="image/jpeg,image/png,image/webp" required><p class="small muted">A foto será reduzida para ocupar menos espaço.</p>',async v=>{const file=$('#photoFile').files[0];if(!file||!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('Escolha uma imagem JPG, PNG ou WebP de até 15 MB.');const bitmap=await createImageBitmap(file),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const dataUrl=canvas.toDataURL('image/jpeg',.7);if(dataUrl.length>1000000)throw Error('A foto ficou grande demais. Escolha uma imagem menor.');if(change(d=>d.photos.push({id:uid(),date:v.date,name:v.name,dataUrl}))){closeModal();render()}})}
async function offlineLibrary(){modal('VIA sem internet',`<p>Baixe as ilustrações dos treinos, todos os brasões e o PDF para consultar sem conexão. Cerca de 65 MB; a disponibilidade depende do espaço do aparelho.</p><progress id="offlineProgress" value="0" max="1"></progress><p id="offlineStatus">Pronto para baixar.</p><button class="btn full" id="offlineDownload">Baixar materiais</button>`);$('#offlineDownload').onclick=async()=>{const b=$('#offlineDownload');b.disabled=true;try{if(!('caches'in window)||location.protocol==='file:')throw Error('Abra o VIA pelo endereço publicado para guardar os materiais offline.');const files=await fetch('offline-assets.json').then(r=>{if(!r.ok)throw Error('Lista de materiais indisponível.');return r.json()}),cache=await caches.open('via-library-v1');let finished=0,errors=0;const todo=[...files];await Promise.all(Array.from({length:4},async()=>{while(todo.length){const path=todo.shift();try{if(!await cache.match(path)){const response=await fetch(path);if(!response.ok)throw Error('download');await cache.put(path,response)}}catch{errors++}finished++;if($('#offlineProgress')){$('#offlineProgress').max=files.length;$('#offlineProgress').value=finished;$('#offlineStatus').textContent=`${finished} de ${files.length} materiais guardados${errors?' · '+errors+' pendentes':''}.`}}}));if(errors)throw Error('Alguns arquivos ficaram pendentes. Tente novamente com conexão e espaço disponíveis.');if($('#offlineStatus'))$('#offlineStatus').textContent='Materiais disponíveis sem internet neste aparelho.';toast('Materiais guardados para usar offline.')}catch(e){if($('#offlineStatus'))$('#offlineStatus').textContent=e.message}finally{b.disabled=false}}}
async function setupPWA(){if(!('serviceWorker'in navigator)||!['https:','http:'].includes(location.protocol))return;try{const reg=await navigator.serviceWorker.register('./sw.js');reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)toast('Uma atualização do VIA ficará pronta ao fechar e abrir o aplicativo.')})})}catch{toast('O modo offline não pôde ser preparado. Tente novamente com conexão.')}}

function privacyView(){return privacyViewV4().replace('Credenciais usam derivação com sal, mas dados de saúde e backups não são criptografados.','Credenciais usam derivação com sal. Os registros dentro do navegador não são criptografados; os novos backups são protegidos com a senha escolhida na exportação.').replace('localStorage é apenas demonstração: o login local não protege contra quem tem acesso ao navegador.','O login local separa perfis, mas não impede o acesso aos arquivos do navegador por quem controla o aparelho.').replace('O que é simulado','Recursos e limites desta versão').replace('Fotos de progresso são marcadores, sem câmera ou galeria real. Lembretes aparecem apenas com o HTML aberto.','Fotos podem ser escolhidas da galeria. Os lembretes são verificados enquanto o app está aberto e em execução; não há alarme agendado com o app fechado.').replace('Login e cadastro são locais, sem confirmação de e-mail ou recuperação remota.','Login e cadastro são locais, sem confirmação de e-mail. O código de recuperação redefine a senha do perfil neste aparelho. Não há sincronização na nuvem.');}

// Startup. Same account storage keys preserve an existing profile on the same origin.
for(const a of Object.values(accounts))if(a.data)migrateData(a.data);
try{document.documentElement.dataset.theme=localStorage.getItem('via.theme')||'light'}catch{}
$('#modal').addEventListener('close',()=>{document.querySelectorAll('.point.selected').forEach(x=>x.classList.remove('selected'));if(workSession&&!workSession.done&&route==='movement')render()});
document.addEventListener('change',e=>{if(['f_histkind','f_histfrom','f_histto'].includes(e.target.id)&&$('#treatmentHistory'))treatmentHistory()});
document.addEventListener('pointerdown',unlockAudio,{once:true});
window.addEventListener('storage',e=>{if(e.key===STORAGE){logout(false);try{accounts=JSON.parse(e.newValue||'{}')}catch{accounts={}}welcomeView();toast('Dados atualizados em outra aba. Entre novamente para continuar.')}});
setInterval(notificationTick,15000);
let session;try{session=sessionStorage.getItem(SESSION)||localStorage.getItem(SESSION)}catch{}
if(session&&accounts[session])enter(session,localStorage.getItem(SESSION)===session,false);else welcomeView();
setupPWA();
